### ISSUE TITLE
Mention v2

### ISSUE THREAD

**Issue by cbarraford** [gernest/mention#13]
@gernest i've refactored the code base again to give us more information about the tags other than just what they are. We now return (in v2 branch) a struct rather than strings.

Heres what i'm thinking... we create a new branch called v1 from master, and have that branch be the default branch for the repo, but also have v2 (which has breaking changes) that people can import via `go get github.com/gernest/mention.v2` or get original version via `go get github.com/gernest/mention.v1` or not include a version at all. Thoughts on versioning this repo?

Thoughts on the changes in v2??

**Comment by gernest** [comment]
@cbarraford  nice work. Have you considered that maybe we can use git tags? I mean using github releases .

That way we will not worry much about  how we introduce the breaking changes, and in the process not worry about tracking branches.

I agree there will be lots of code will be affected if we merge the branch upstream.

**Comment by gernest** [comment]
Plus they work nicely with `dep` tool. I am not sure how we will roll this out though, so any thoughts on this?

One option is , we tag the current HEAD to `v1.0.0` then merge the v2 branch, then we again tag the resulting HEAD to `v2.0.0`.

**Comment by gernest** [comment]
I merged v2 branch to master. Now we use tags to refer to different versions. For the v1  use tag `v1.0.0`
