### ISSUE TITLE
Using apostrophe

### ISSUE THREAD

**Issue by kfreiman** [gernest/mention#18]
Right side after apostrophe should't be a part of hashtag.
In case of `@bob's cookies` only `@bob` is tag.

**Comment by arp242** [comment]
Does it not work if you add it to the terminator list?

    mention.GetTags('@', v.src, '\'')

Maybe it might be useful to export a `CommonEndTags` or `TwitterEndTags` or some such>

We currently use this, which has been working well for us:

```
var endChars = []rune{'!', '#', '$', '%', '&', '*', '(', ')', '+', '=', '<',
	'>', '?', '/', ':', ';', '\'', '"', ',', '-', '.'}
```

**Comment by kfreiman** [comment]
@Carpetsmoker thanks, it works. I didn't see this option(
