### ISSUE TITLE
tag with space should be ignore

### ISSUE THREAD

**Issue by kkdai** [gernest/mention#4]
"how does it feel to be rejected? #loner tt ggg sjdsj dj  #link"
`[loner linker]`

"how does it feel to be rejected? # it is #loner tt ggg sjdsj dj  #linker"
Expect: `[loner linker]` 
Got: `[ it is #loner tt ggg sjdsj dj  #linker]`

**Comment by gernest** [comment]
@kkdai thanks for reporting. I just made the fix, you can reopen this issue if it is not yet resolved for you.
